### ISSUE TITLE
LS Commerce service: appjson.svc missing

### ISSUE THREAD

**Issue by reiyc** [lsretail/omni-server-latest#5]
Dear lsretail,

I've done a modification to the LS Commerce service and built the Solution resulting in an updated setup file. However, when I install this modified version of the LS Commerce service, the Appjson.svc is missing. 

Ping URL: http://localhost/LSCommerceService/appjson.svc/ping
Results in: Resource cannot be found and when I browse to the LS Commerce installation folder this file is missing.

I also noticed that the Service project does not contain this file.

Please assist. What is the correct way to build and produce the installer, and where can the appjson.svc be found.

**Comment by LSKristjan** [comment]
Open source project can use ucjson.svc for ping test, appjson is only available in Retail released version.
http://localhost/LSCommerceService/ucjson.svc/ping
